// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEwQga-ISY-j62eYs115ZCHxz-N17tWTo',
    appId: '1:1077286598533:web:b0df82c8b0b7d3d89936ec',
    messagingSenderId: '1077286598533',
    projectId: 'sheebasample-fbbb2',
    authDomain: 'sheebasample-fbbb2.firebaseapp.com',
    storageBucket: 'sheebasample-fbbb2.appspot.com',
    measurementId: 'G-F63BT1799F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtBnbztVyNH7EBGRZLZ1BgVFNldOw0cLI',
    appId: '1:1077286598533:android:19a1a90cf2983b9a9936ec',
    messagingSenderId: '1077286598533',
    projectId: 'sheebasample-fbbb2',
    storageBucket: 'sheebasample-fbbb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_WYJLQpfWbHbK3fWqN56KRqKakQrXdww',
    appId: '1:1077286598533:ios:eb74057ae4b9dbf79936ec',
    messagingSenderId: '1077286598533',
    projectId: 'sheebasample-fbbb2',
    storageBucket: 'sheebasample-fbbb2.appspot.com',
    iosBundleId: 'com.hiroki.sheebaSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_WYJLQpfWbHbK3fWqN56KRqKakQrXdww',
    appId: '1:1077286598533:ios:eb74057ae4b9dbf79936ec',
    messagingSenderId: '1077286598533',
    projectId: 'sheebasample-fbbb2',
    storageBucket: 'sheebasample-fbbb2.appspot.com',
    iosBundleId: 'com.hiroki.sheebaSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEwQga-ISY-j62eYs115ZCHxz-N17tWTo',
    appId: '1:1077286598533:web:fad25a61d1b1d70e9936ec',
    messagingSenderId: '1077286598533',
    projectId: 'sheebasample-fbbb2',
    authDomain: 'sheebasample-fbbb2.firebaseapp.com',
    storageBucket: 'sheebasample-fbbb2.appspot.com',
    measurementId: 'G-GGHR5WBXK2',
  );
}
